stdevOsmel t4 pincode backspace
skycoin/skycoin-mobilewallet pull request #27
Opened 2018-01-08 16:24 UTC by stdevOsmel

Added backspace for pingcode keyboard

2018-01-09 11:20 UTC, samuelvisscher requested changes

2018-01-09 11:20 UTC, samuelvisscher commented on src/pages/pincode/pincode.ts
> -import { Component, ElementRef } from '@angular/core';
Please leave existing bracket spacing

2018-01-09 11:20 UTC, samuelvisscher commented on src/pages/pincode/pincode.ts
> -  constructor(
Please leave existing indentation

2018-01-09 18:19 UTC, stdevOsmel commented on src/pages/pincode/pincode.ts
> -import { Component, ElementRef } from '@angular/core';
resolved

2018-01-09 18:21 UTC, stdevOsmel commented on src/pages/pincode/pincode.ts
> -  constructor(
resolved

2018-01-10 18:37 UTC, samuelvisscher commented
Excellent, could you please make this PR against dev?

2018-01-11 14:05 UTC, stdevErnesto commented
Please close this PR, we do not need it in develop branch!!

2018-01-11 15:01 UTC, closed without merging