stdevOsmel t21 list transactions
skycoin/skycoin-mobilewallet pull request #32
Opened 2018-01-09 17:17 UTC by stdevOsmel

The layout of the transaction list was created

2018-01-09 18:57 UTC, samuelvisscher requested changes
Why don't we use the standard Angular date format pipe or alternatively momentjs?

2018-01-09 18:57 UTC, samuelvisscher commented on src/pipes/sky-date/sky-date.ts
> +    let _value: string = '';
dont use let for vars that are not reassigned
dont type hint when its automatically deduced
dont prefix protected vars with _, use private scope for properties tho

2018-01-10 18:37 UTC, samuelvisscher commented
Also, could you please make this PR against dev?

2018-01-11 14:05 UTC, stdevErnesto commented
Please close this PR, we do not need it in develop branch!!

2018-01-11 14:10 UTC, closed without merging