Ernestomr87 t38 create button component
skycoin/skycoin-mobilewallet pull request #46
Opened 2018-01-12 17:28 UTC by stdevErnesto

[mobilewallet] refs#38 Create Mobile Wallet

2018-01-15 17:30 UTC, samuelvisscher requested changes
As discussed in telegram, please write the component to be in line with our current button component:

https://github.com/samuelvisscher/skycoin/tree/develop/src/gui/static/src/app/components/layout/button

2018-01-16 16:02 UTC, ernestomr87 commented
Done !!
"As discussed in telegram, please write the component to be in line with our current button component"

2018-01-23 00:27 UTC, samuelvisscher approved these changes

2018-01-23 00:27 UTC, samuelvisscher commented on src/components/button/button.component.ts
> +  @Input() error: string;
Let's manage error & state similar to: https://github.com/skycoin/skycoin/blob/develop/src/gui/static/src/app/components/layout/button/button.component.ts

2018-01-23 00:27 UTC, samuelvisscher commented on src/components/button/button.component.ts
> +import {Component, EventEmitter, Input, Output} from '@angular/core';
add space ..

2018-01-23 00:27 UTC, merged