Ernestomr87 t40 custom modal
skycoin/skycoin-mobilewallet pull request #49
Opened 2018-01-21 23:22 UTC by stdevErnesto

Finish	    refs#40 skycoin/skycoin-mobilewallet Create Modal Component
Finish	    refs#31 skycoin/skycoin-mobilewallet On-boarding " Modal Disclaimer Create/Load Wallet"

2018-01-22 16:09 UTC, samuelvisscher requested changes

2018-01-22 16:09 UTC, samuelvisscher commented on src/pages/pincode/pincode.ts
> +    // this.generateSeed();
We should not add commented code

2018-01-22 16:09 UTC, samuelvisscher commented on src/pages/wallet-detail/wallet-detail.html
> +<modal (close)="closeModal()" [header]="'View QR Code'" *ngIf="address" [footer]="'B9UG4KcdGdNRScAt5GxxJvX4J89S5vkRcY'">
Are you sure this is correct?

2018-01-22 16:09 UTC, samuelvisscher commented on src/theme/variables.scss
> +  src: url('../../assets/custom-fonts/MontrealRegular.ttf') format('truetype');
We can remove montreal

2018-01-22 16:09 UTC, samuelvisscher commented on src/theme/variables.scss
> +  font-family: 'Work Sans';
I dont think we should be using work sans anywhere?

2018-01-22 16:47 UTC, stdevErnesto commented on src/theme/variables.scss
> +  font-family: 'Work Sans';
![image](https://user-images.githubusercontent.com/34870398/35232623-f46aef2c-ff69-11e7-9725-51f6d1b6bd87.png)

2018-01-23 00:29 UTC, samuelvisscher approved these changes

2018-01-23 00:29 UTC, merged