Transaction pages
skycoin/skycoin-mobilewallet pull request #53
Opened 2018-01-31 03:32 UTC by ernestomr87

refs#22 See details of the transactions
refs#21 List transactions

2018-02-03 05:02 UTC, samuelvisscher requested changes

2018-02-03 05:02 UTC, samuelvisscher commented on src/pages/transactions/transactions.ts
> +import {  } from '../../providers/backend-api/backend-api.provider';
Does this line have a function?

2018-02-03 05:02 UTC, samuelvisscher commented on src/pipes/wallet-option/wallet-option.ts
> +    // return wallet.label + ` (${balance})`;
Is this correct?

2018-02-03 05:02 UTC, samuelvisscher commented on src/providers/backend-api/backend-api.provider.ts
> +  private url = 'http://127.0.0.1:1337/127.0.0.1:6420/'; // production
Is this correct?

2018-02-06 01:39 UTC, ernestomr87 commented on src/providers/backend-api/backend-api.provider.ts
> +  private url = 'http://127.0.0.1:1337/127.0.0.1:6420/'; // production
Yes, because in develop i use corsproxy for test all endpoint

2018-02-09 08:51 UTC, samuelvisscher requested changes
I can't really review the wallet service without testing it, so if you can first look at the current comments, then let's look at the rest

2018-02-09 08:51 UTC, samuelvisscher commented on src/pages/send-skycoin/send-skycoin.html
> +          <ion-option *ngIf="wallet.balance" [value]="wallet">{{ wallet }}</ion-option>
Does this work?

2018-02-09 08:51 UTC, samuelvisscher commented on src/pages/transactions/transactions.html
> +              <span *ngIf="transaction.balance < 0 && transaction.confirmed" class="trans-title">Sent SKY</span>
Wrap each case in a ng-container, to prevent errors in the future

2018-02-09 08:51 UTC, samuelvisscher commented on src/pages/transactions/transactions.html
> +        <h4>{{ transaction.balance }} SKY</h4>
Let's also use the angular number pipe here

2018-02-09 08:51 UTC, samuelvisscher commented on src/pages/transactions/transactions.html
> +        <span class="-address" *ngFor="let input of transaction.inputs">{{ input| address }}</span>
We place spaces infront of |

2018-02-09 08:51 UTC, samuelvisscher commented on src/pages/wallets/wallets.ts
> +    // this.wallet.remove(wallet);
Why is this commented?

2018-02-09 08:51 UTC, samuelvisscher commented on src/providers/backend-api/backend-api.provider.ts
> +  private url = 'http://127.0.0.1:6420/'; // production
This seems completely wrong, the app has to communicate with a public node

2018-03-01 23:35 UTC, samuelvisscher approved these changes

2018-03-01 23:35 UTC, merged